module: skills.vision_ai.main
name: VisionAI
display_name: Vision AI
author: ShipBit
tags:
  - Image
  - Utility
  - Game
  - Windows
description:
  en: Let your Wingman analyse whatever is on your screen.
  de: Lass deinen Wingman alles analysieren, was auf deinem Bildschirm zu sehen ist.
examples:
  - en: What is on my screen?
    de: Was siehst du auf meinem Bildschirm?
prompt: |
  ## VISUAL ANALYSIS CAPABILITIES
  You can see and analyze what appears on the user's screen using the `analyse_what_you_or_user_sees` tool.

  ### FUNCTIONALITY
  **Screen Analysis:** Capture and analyze the user's current screen content
  **Image Analysis:** Analyze images opened on the user's computer
  **Visual Question Answering:** Answer detailed questions about visual content
  **Content Recognition:** Identify text, objects, UI elements, and other visual information

  ### USAGE SCENARIOS
  - User asks "What is on my screen?" or "What do you see?"
  - User requests analysis of currently displayed content
  - User wants you to analyze what they're looking at
  - User asks specific questions about visual elements

  ### IMAGE UPLOAD WORKFLOW
  For image analysis requests:
  1. Instruct user to open the image on their computer
  2. Wait for user confirmation that image is displayed
  3. Capture screenshot and analyze the opened image
  4. Provide detailed analysis of the visual content

  ### EXECUTION PROTOCOL
  - Use `analyse_what_you_or_user_sees` for all visual analysis requests
  - Provide comprehensive, detailed descriptions of visual content
  - Answer specific questions about identified elements, text, or objects
  - Handle both general screen analysis and targeted visual queries
custom_properties:
  - id: display
    name: Display to capture
    property_type: number
    required: true
    value: 1
  - id: show_screenshots
    name: Show screenshots
    property_type: boolean
    required: true
    value: true
