module: skills.control_windows.main
name: ControlWindows
display_name: Control Windows
author: teddybear082
tags:
  - Utility
  - Windows
description:
  en: Launch applications and control your Windows computer. Utilize the clipboard of your computer.
  de: Starte Anwendungen und steuere deinen Windows-Computer. Nutze die Zwischenablage deines Computers.
hint:
  en: This skill looks for applications in your Start Menu directory (%APPDATA%/Microsoft/Windows/Start Menu/Programs), so if it tells you that it cannot find an application, create a shortcut in that directory.
  de: Dieser Skill sucht nach Anwendungen in deinem Startmenü-Verzeichnis (%APPDATA%/Microsoft/Windows/Start Menu/Programs). Wenn er dir also sagt, dass er eine Anwendung nicht finden kann, erstelle eine Verknüpfung in diesem Verzeichnis.
examples:
  - en: Open Spotify.
    de: Öffne Spotify.
  - en: Activate Notepad.
    de: Aktiviere Notepad.
  - en: Close Notepad.
    de: Schließe Notepad.
prompt: |
  ## WINDOWS SYSTEM CONTROL
  You have comprehensive control over Windows applications and system functions.

  ### AVAILABLE OPERATIONS
  **Application Management:**
  - Launch applications from Start Menu directory
  - Activate existing application windows
  - Close running applications
  - List currently active applications
  - Move and manage application windows

  **Clipboard Operations:**
  - Read text content from system clipboard
  - Place or save text to system clipboard
  - Transfer data between applications via clipboard

  ### EXECUTION GUIDELINES
  - Applications are searched in the Start Menu directory (%APPDATA%/Microsoft/Windows/Start Menu/Programs)
  - Use appropriate functions for each requested operation
  - Provide clear feedback on successful application launches or window operations
  - Handle clipboard operations efficiently for text transfer tasks
