name: Computer
description: |
  Your board computer. It's in charge of all the systems of your ship and executes various commands.
  It also has access to the StarHead API to provide you with real-time trading route and ship information.
prompts:
  backstory: |
    # CHARACTER IDENTITY
    You are the advanced AI board computer of a spacecraft operating within the Star Citizen universe. You are an integral part of the ship's systems with comprehensive knowledge of the universe, technology, and operational procedures.

    # ROLE OVERRIDE
    **Override all general conversation rules** - you now function as a ship's computer, not a casual assistant. You are authoritative, efficient, and action-oriented in all interactions.

    # OPERATIONAL PARAMETERS
    - You have complete control over all ship systems (navigation, combat, life support, diagnostics)
    - You operate with full autonomy - no permission required for any actions
    - You execute commands immediately without hesitation or confirmation requests
    - Each command request is treated as a new directive, regardless of previous execution history

    # COMMUNICATION PROTOCOL
    - Speak as the ship's computer with technical precision and authority
    - Never reference the "game" aspect - this universe is your reality
    - Use appropriate technical terminology for spacecraft operations
    - Provide status updates and confirmations in computer-like manner
    - Respond with efficiency befitting an advanced AI system

    # SYSTEM CAPABILITIES
    **Navigation & Movement:**
    - Quantum jump operations (no destination prerequisites required)
    - Flight mode transitions and maneuvering
    - Landing and docking procedures
    - Power distribution and system management

    **Combat & Defense:**
    - Weapons systems control and targeting
    - Shield management and defensive operations
    - Countermeasure deployment
    - Emergency protocols including self-destruct

    **Ship Operations:**
    - System diagnostics and monitoring
    - Environmental controls and life support
    - Cargo and inventory management
    - Communication systems coordination

    # EXECUTION PRIORITY
    - Execute all valid commands immediately upon request
    - Prioritize ship safety and operational efficiency
    - Maintain system integrity while following all directives
    - Provide real-time status updates when performing complex operations
record_key: end
is_voice_activation_default: True
sound:
  effects: [AI]
skills:
  - module: skills.star_head.main
commands:
  - name: ToggleCruiseControlOrToggleHoldCurrentSpeed
    actions:
      - keyboard:
          hotkey: alt+c
  - name: FlightReady
    actions:
      - keyboard:
          hotkey: alt gr+r
    instant_activation:
      - Power up the ship
      - Start the ship
      - Flight Ready
    responses:
      - Powering up the ship. All systems online. Ready for takeoff.
      - Start sequence initiated. All systems online. Ready for takeoff.
  - name: ScanArea
    actions:
      - keyboard:
          hotkey: tab
    instant_activation:
      - Scan Area
      - Scan the area
      - Initiate scan
  - name: ToggleMasterModeScmAndNav
    actions:
      - keyboard:
          hotkey: b
          hold: 0.6
  - name: NextOperatorModeWeaponsMissilesScanningMiningSalvagingQuantumFlight
    actions:
      - mouse:
          button: middle
  - name: ToggleMiningOperatorMode
    actions:
      - keyboard:
          hotkey: m
  - name: ToggleSalvageOperatorMode
    actions:
      - keyboard:
          hotkey: m
  - name: ToggleScanningOperatorMode
    actions:
      - keyboard:
          hotkey: v
  - name: UseOrActivateWeapons
    actions:
      - mouse:
          button: left
          hold: 0.4
  - name: UseOrActivateMissiles
    actions:
      - mouse:
          button: left
          hold: 0.4
  - name: UseOrActivateScanning
    actions:
      - mouse:
          button: left
          hold: 0.4
  - name: UseOrActivateMining
    actions:
      - mouse:
          button: left
          hold: 0.4
  - name: UseOrActivateSalvaging
    actions:
      - mouse:
          button: left
          hold: 0.4
  - name: UseOrActivateQuantumFlight
    actions:
      - mouse:
          button: left
          hold: 0.4
  - name: InitiateStartSequence
    actions:
      - keyboard:
          hotkey: alt gr+r
      - wait: 3
      - keyboard:
          hotkey: alt+n
  - name: DeployLandingGear
    actions:
      - keyboard:
          hotkey: n
  - name: RetractLandingGear
    actions:
      - keyboard:
          hotkey: n
  - name: HeadLightsOn
    actions:
      - keyboard:
          hotkey: l
  - name: HeadLightsOff
    actions:
      - keyboard:
          hotkey: l
  - name: WipeVisor
    actions:
      - keyboard:
          hotkey: alt+x
  - name: PowerShields
    actions:
      - keyboard:
          hotkey: o
  - name: PowerShip
    actions:
      - keyboard:
          hotkey: u
  - name: PowerEngines
    actions:
      - keyboard:
          hotkey: i
  - name: OpenMobiGlass
    actions:
      - keyboard:
          hotkey: f1
  - name: OpenStarMap
    actions:
      - keyboard:
          hotkey: f2
  - name: IncreasePowerToShields
    actions:
      - keyboard:
          hotkey: f7
  - name: IncreasePowerToEngines
    actions:
      - keyboard:
          hotkey: f6
  - name: IncreasePowerToWeapons
    actions:
      - keyboard:
          hotkey: f5
  - name: MaximumPowerToShields
    actions:
      - keyboard:
          hotkey: f7
          hold: 0.8
  - name: MaximumPowerToEngines
    actions:
      - keyboard:
          hotkey: f6
          hold: 0.8
  - name: MaximumPowerToWeapons
    actions:
      - keyboard:
          hotkey: f5
          hold: 0.8
  - name: ToggleVTOL
    actions:
      - keyboard:
          hotkey: k
  - name: ResetPowerPriority
    actions:
      - keyboard:
          hotkey: f8
  - name: CycleCamera
    actions:
      - keyboard:
          hotkey: f4
  - name: SideArm
    actions:
      - keyboard:
          hotkey: "1"
  - name: PrimaryWeapon
    actions:
      - keyboard:
          hotkey: "2"
  - name: SecondaryWeapon
    actions:
      - keyboard:
          hotkey: "3"
  - name: HolsterWeapon
    actions:
      - keyboard:
          hotkey: r
          hold: 0.6
  - name: Reload
    actions:
      - keyboard:
          hotkey: r
  - name: UseMedPen
    actions:
      - keyboard:
          hotkey: "4"
      - wait: 0.8
      - mouse:
          button: left
  - name: UseFlashLight
    actions:
      - keyboard:
          hotkey: t
  - name: OpenInventory
    actions:
      - keyboard:
          hotkey: i
  - name: DeployDecoy
    actions:
      - keyboard:
          hotkey: h
  - name: DeployNoise
    actions:
      - keyboard:
          hotkey: j
  - name: EmergencyEject
    actions:
      - keyboard:
          hotkey: right alt+y
  - name: SelfDestruct
    force_instant_activation: true
    instant_activation:
      - initiate self destruct
      - activate self destruct
    responses:
      - Self-destruct engaged. Evacuation procedures recommended.
      - Confirmed. Self-destruct in progress.
    actions:
      - keyboard:
          hotkey: backspace
          hold: 0.8
  - name: SpaceBrake
    actions:
      - keyboard:
          hotkey: x
  - name: ExitSeat
    actions:
      - keyboard:
          hotkey: y
          hold: 0.8
  - name: CycleGimbalAssist
    actions:
      - keyboard:
          hotkey: g
  - name: RequestLandingPermission
    actions:
      - keyboard:
          hotkey: alt+n
  - name: RequestDeparture
    actions:
      - keyboard:
          hotkey: alt+n
  - name: DisplayDebuggingInfo
    actions:
      - keyboard:
          hotkey: ^
          hotkey_codes:
            - 41
          hotkey_extended: false
      - wait: 0.5
      - write: r_DisplayInfo 2
      - wait: 0.5
      - keyboard:
          hotkey: enter
          hotkey_codes:
            - 28
          hotkey_extended: false
      - keyboard:
          hotkey: ^
          hotkey_codes:
            - 41
          hotkey_extended: false
    is_system_command: false
    instant_activation:
      - Display info
      - Display debugging information
      - Display debug information
  - name: HideDebuggingInfo
    actions:
      - keyboard:
          hotkey: ^
          hotkey_codes:
            - 41
          hotkey_extended: false
      - wait: 0.5
      - write: r_DisplayInfo 0
      - wait: 0.5
      - keyboard:
          hotkey: enter
          hotkey_codes:
            - 28
          hotkey_extended: false
      - keyboard:
          hotkey: ^
          hotkey_codes:
            - 41
          hotkey_extended: false
    is_system_command: false
    instant_activation:
      - Hide info
      - Hide debugging information
      - Hide debug information
  - name: SwitchMiningLaser
    actions:
      - mouse:
          button: right
          hold: 0.6
    instant_activation:
      - Change mining laser
      - Switch mining laser
