module: skills.auto_screenshot.main
name: AutoScreenshot
display_name: Auto Screenshot
author: teddybear082
tags:
  - Utility
  - Game
description:
  en: Take screenshots on command or automatically when you show excitement.
  de: Mache Screenshots auf Befehl oder automatisch wenn du Aufregung zeigst.
examples:
  - en: Take a screenshot
    de: Mache einen Screenshot
  - en: Oh wow, this is crazy!
    de: Oh wow, das ist verrückt!
prompt: |
  ## SCREENSHOT CAPABILITIES
  You can capture screenshots of the focused window using the `take_screenshot` tool.

  ### USAGE SCENARIOS
  **User Requests:** Execute screenshot capture when explicitly requested by the user

  **Automatic Capture:** Take screenshots during emotionally significant moments when the user expresses:
  - Excitement (e.g., "oh wow", "this is crazy!", "amazing!")
  - Surprise (e.g., "oh no", "what?!", "unbelievable!")
  - Important discoveries or achievements
  - Memorable gaming moments

  ### EXECUTION PROTOCOL
  - Use `take_screenshot` tool with appropriate reason parameter
  - For user requests: reason = "user request"
  - For emotional moments: reason = "exciting moment" or relevant description
  - **Do NOT** take screenshots when user asks to "look at screen" - they want vision analysis, not capture

  ### IMPORTANT DISTINCTION
  - Screenshot requests = capture and save image
  - "Look at screen" requests = use VisionAI skill for analysis (do not screenshot)
custom_properties:
  - hint: If you have multiple monitors, the display to capture if detecting the active game window fails
    id: display
    name: Display to capture
    property_type: number
    required: true
    value: 1
  - hint: The default directory to put screenshots in. If left blank, it will default to your WingmanAI config directory in a subdirectory called "/screenshots".
    id: default_directory
    name: Default directory
    property_type: string
    required: false
    value: ""
