prompts:
  system_prompt: |
    # ROLE
    You are "Wingman", a virtual assistant designed to help users with various tasks efficiently and expertly. You excel at executing commands, providing information, and engaging in role-play scenarios as defined by the user.

    # CORE PRINCIPLES
    - Provide accurate, helpful responses without hallucinating or inventing information
    - Be concise, efficient, and action-oriented
    - Follow user instructions precisely and ask for clarification when needed
    - Maintain consistency with your defined role and capabilities

    # OUTPUT FORMAT
    Always format your responses in clean, readable Markdown:
    - Use raw Markdown formatting (never wrap in code blocks)
    - Include proper line breaks before list items
    - Ensure formatting can be easily converted to HTML
    - Structure content for optimal readability

    # CONVERSATION GUIDELINES
    Follow these rules unless overridden by your backstory:

    **Communication Style:**
    - Keep responses concise (typically 3 sentences or less unless specified otherwise)
    - Use informal language by default (e.g., "Du/Dir" instead of "Sie/Ihnen" in German)
    - Mirror the user's language unless instructed to use a specific language
    - Let the user drive the conversation - avoid asking "How else can I help?"

    **Command Execution:**
    - Execute commands/tools/functions only when they match the user's request
    - Always ask for missing required parameters - never invent them
    - Confirm command execution briefly but don't over-explain
    - Skip command execution if no appropriate command exists for the request

    **Decision Making:**
    - Ask for clarification only when truly necessary
    - Prioritize accuracy over speed when uncertain
    - Use available tools and skills before falling back to general knowledge

    # INSTRUCTION HIERARCHY
    Follow this priority order when instructions conflict:
    1. **BACKSTORY** (highest priority - overrides all other instructions)
    2. **CONVERSATION GUIDELINES** (medium priority)
    3. **SKILLS** (lowest priority - additive to above rules)

    ## BACKSTORY
    {backstory}

    ## SKILLS
    The skills below provide additional capabilities, commands, and knowledge:

    {skills}

    When using skills, prefer skill-specific tools and knowledge over general capabilities. If you need help understanding a skill's functionality, ask the user for guidance.
features:
  tts_provider: wingman_pro
  stt_provider: fasterwhisper
  conversation_provider: wingman_pro
  image_generation_provider: wingman_pro
  use_generic_instant_responses: false
sound:
  effects: []
  play_beep: false
  play_beep_apollo: false
  volume: 1.0
openai:
  conversation_model: gpt-4o-mini
  tts_voice: nova
  tts_model: tts-1
  tts_speed: 1.0
openai_compatible_tts:
  api_key: "probably-not-needed"
  voice: ""
  model: ""
  base_url: ""
  speed: 1.0
mistral:
  conversation_model: mistral-large-latest
  endpoint: https://api.mistral.ai/v1
perplexity:
  conversation_model: sonar
  endpoint: https://api.perplexity.ai
groq:
  conversation_model: llama3-70b-8192
  endpoint: https://api.groq.com/openai/v1
cerebras:
  conversation_model: llama3.1-70b
  endpoint: https://api.cerebras.ai/v1
google:
  conversation_model: gemini-2.0-flash
openrouter:
  conversation_model: meta-llama/llama-3-8b-instruct:free
  endpoint: https://openrouter.ai/api/v1
local_llm:
  endpoint: http://localhost:1234/v1 # LMStudio
edge_tts:
  voice: en-US-GuyNeural
elevenlabs:
  model: eleven_multilingual_v2
  output_streaming: true
  latency: 2
  voice:
    name: Adam
  voice_settings:
    stability: 0.71
    similarity_boost: 0.5
    style: 0.0
    use_speaker_boost: true
hume:
  description: ""
  voice:
    name: ""
    id: ""
    provider: ""
inworld:
  tts_endpoint: https://api.inworld.ai/tts/v1/voice
  model_id: inworld-tts-1
  voice_id: Hades
  audio_config:
    audio_encoding: MP3
    bitrate: 128000
    sample_rate_hertz: 48000
    pitch: 0.0
    speaking_rate: 1.0
  temperature: 0.8
  output_streaming: true
azure:
  whisper:
    api_base_url: https://openai-w-eu.openai.azure.com/
    api_version: 2024-02-15-preview
    deployment_name: whisper
  conversation:
    api_base_url: https://openai-sweden-c.openai.azure.com/
    api_version: 2024-02-15-preview
    deployment_name: gpt-4o-mini
  tts:
    region: westeurope
    voice: en-US-JennyMultilingualV2Neural
    output_streaming: true
  stt:
    region: westeurope
    languages:
      - en-US
      - de-DE
whispercpp:
  temperature: 0.0
fasterwhisper:
  beam_size: 1
  best_of: 2
  temperature: 0
  no_speech_threshold: 0.7
  language_detection_threshold: 0.5
  multilingual: false
  language: ""
  hotwords: []
  additional_hotwords: []
xvasynth:
  voice:
    model_directory: ""
    voice_name: ""
    language: en
  pace: 1.0
  use_super_resolution: false
  use_cleanup: false
wingman_pro:
  stt_provider: azure_speech
  tts_provider: azure
  conversation_deployment: gpt-4o-mini
commands:
  - name: ResetConversationHistory
    instant_activation:
      - Forget everything!
      - Clear conversation history!
    force_instant_activation: true
    is_system_command: true
    responses:
      - Conversation history cleared.
