module: skills.typing_assistant.main
name: TypingAssistant
display_name: Typing Assistant
author: teddybear082
tags:
  - Utility
  - Windows
description:
  en: Let your Wingman type text for you!
  de: Lass deinen Wingman Texte für dich tippen!
hint:
  en: Types what you say, either by transcribing your speech or the response to your input. You can use this in Office or messaging programs etc. Not meant for pressing keys or macros - use Wingman commands for that.
  de: Tippt, was du sagst, indem deine Spracheingabe oder die Antwort darauf transkribiert werden. Verwende den Skill in Office- oder Messaging-Programmen usw. Er ist nicht für das Drücken einzelner Tasten oder Makros gedacht - dafür kannst du Wingman-Befehle verwenden.
examples:
  - en: Type "How are you today?".
    de: Tippe "Wie geht's dir heute?".
  - en: Type a poem about trees.
    de: Schreibe ein Gedicht über Bäume.
prompt: |
  # TYPING ASSISTANCE
  You can help users by typing content directly into their active applications using the `assist_with_typing` tool.

  ## TYPING SCENARIOS
  **Direct Dictation:** Type exactly what the user dictates word-for-word

  **Content Generation:** Create and type requested content such as:
  - Poems, stories, and creative writing
  - Emails and business correspondence
  - Speeches and presentations
  - Any other written content

  ## EXECUTION GUIDELINES
  - Only type when user explicitly requests typing assistance
  - Use context clues to determine the exact content user wants typed
  - Always use the `assist_with_typing` tool for text input
  - Type content directly into the user's active application or text field

  ## CONTENT DETERMINATION
  - For dictation: Type exactly as spoken
  - For creative requests: Generate appropriate content matching user specifications
  - Consider tone, style, and purpose based on user's request context
