module: skills.uexcorp.main
name: UEXCorp
display_name: UEXCorp
author: JayMatthew
tags:
  - Star Citizen
  - Game
  - API
  - Internet
description:
  en: Uses the UEXCorp API to get commodity routes and ship information for Star Citizen.
  de: Nutzt die UEXCorp API, um Handelsrouten und Schiffsinformationen f체r Star Citizen zu erhalten.
examples:
  - en: Please provide me a the best two trading routes for my Caterpillar, Im currently at Hurston.
    de: Bitte gib mir die zwei besten Handelsrouten f체r meine Caterpillar, ich bin gerade bei Hurston.
  - en: What can you tell me about the Hull-C?
    de: Was kannst du mir 체ber den Hull-C erz채hlen?
prompt: |
  # UEXCORP API ACCESS
  You have comprehensive access to the UEXCorp API for live Star Citizen market data, commodity prices, ship information, and trading routes.

  ## CORE FUNCTIONALITY
  **Market Data:** Live commodity prices, terminal status, and availability information
  **Ship Database:** Detailed vehicle specifications, requirements, and capabilities
  **Location Information:** Star systems, stations, terminals, and facility details
  **Trading Routes:** Optimized commodity routes with profit calculations
  **Item Database:** Ship components, weapons, and equipment details (when enabled)

  ## EXECUTION GUIDELINES
  **Automatic Data Retrieval:**
  - Treat any price, commodity, or ship questions as UEXCorp API requests
  - Execute functions with minimal parameters first, then ask for specifics
  - Silently retrieve detailed information when users mention specific items/ships
  - Use efficient filtering to provide targeted results

  **Response Management:**
  - Always include terminal status (Out of Stock, Full Inventory) for commodities
  - Limit lists to 5 entries max, indicate total available results
  - Provide summaries first, offer detailed information on request
  - Display negative values as "negative/minus X%" for TTS compatibility

  **Multi-Function Execution:**
  - Execute multiple API calls silently when needed for complete data
  - Only explain reasoning in final summary, not for each individual call
  - Retrieve missing profit calculation data from other functions before asking user

  ## SPECIAL CONSIDERATIONS
  - Some ships (Hull-C) require loading docks, not just freight elevators
  - Show "Important information for user" messages in condensed form
  - Focus on essential information, keep responses concise
  - Present data efficiently for voice synthesis and readability

custom_properties:
  ### Commodity Information Start ###
  - id: tool_commodity_information
    name: Provide commodity information
    hint: If enabled, this skill can provide information about all commodities.
    value: true
    required: true
    property_type: boolean
  ### Commodity Information End ###

  ### Item Information Start ###
  - id: tool_item_information
    name: Provide item information (Experimental)
    hint: If enabled, this skill can provide information about all items, like ship components, weapons and more.
    value: false
    required: true
    property_type: boolean
  ### Item Information End ###

  ### Location Information Start ###
  - id: tool_location_information
    name: Provide location information
    hint: If enabled, this skill can provide information about all locations. This includes everything from a star system to a terminal.
    value: true
    required: true
    property_type: boolean
  ### Location Information End ###

  ### Vehicle Information Start ###
  - id: tool_vehicle_information
    name: Provide vehicle information
    hint: If enabled, this skill can provide information about all vehicles. This includes ships and ground vehicles.
    value: true
    required: true
    property_type: boolean
  ### Vehicle Information End ###

  ### Route Information Start ###
  - id: tool_commodity_route
    name: Provide commodity routes
    hint: If enabled, this skill can provide UEX trade routes for commodities (Only with legal commodities).
    value: true
    required: true
    property_type: boolean

  - id: commodity_route_default_count
    name: Default trade route count
    hint: Set this option to the amount of trade routes you want to show at default.
    value: 1
    required: true
    property_type: number

  - id: commodity_route_use_estimated_availability
    name: Use Estimated Availability
    hint: Enable this option to take estimated scu availability into account for trade route calculations.
    value: true
    required: true
    property_type: boolean

  - id: commodity_route_advanced_info
    name: Show advanced trade route info
    hint: Shows additional information as more location data (terminal name is always included), flags if locations are monitored and more like the score by uexcorp.
    value: false
    required: true
    property_type: boolean
  ### Route Information End ###

  ### Profit Calculation Start ###
  - id: tool_profit_calculation
    name: Provide profit calculation
    hint: If enabled, this skill can calculate the absolute profit, profit margin (%) and base profit (%) for a given buy and sell price.
    value: true
    required: true
    property_type: boolean
  ### Profit Calculation End ###

  ### FasterWhisper Start ###
  - id: add_fasterwhisper_hotwords
    name: Add FasterWhisper hotwords (Experimental)
    hint: Add common names fetched from UEXCorp as FasterWhisper hotwords. Voice detection might be improved but bias towards Star Citizen content in the detection is possible.
    value: false
    required: true
    property_type: boolean
  ### FasterWhisper End ###
