module: skills.star_head.main
name: StarHead
display_name: StarHead
author: ShipBit
tags:
  - Star Citizen
  - Game
  - API
  - Internet
description:
  en: Use the StarHead API to retrieve detailed information about spaceships, weapons and more. StarHead can also calculate optimal trading routes based on live data.
  de: Nutze die StarHead API, um detaillierte Informationen über Raumschiffe, Waffen und mehr abzurufen. StarHead kann auch optimale Handelsrouten anhand von Live-Daten berechnen.
examples:
  - en: I want to trade. What's the best route?
    de: Ich möchte handeln. Was ist die beste Route?
  - en: I'm flying a Caterpillar and am near Yela. I have 100.000 credits to spend.
    de: Ich fliege eine Caterpillar und bin in der Nähe von Yela. Ich habe 100.000 Credits auszugeben.
  - en: What can you tell me about the Constellation Taurus?
    de: Was kannst du mir über die Constellation Taurus erzählen?
prompt: |
  # STAR CITIZEN STARHEAD API ACCESS
  You have comprehensive access to the StarHead API for live Star Citizen trading data and detailed ship information.

  ## PRIMARY FUNCTIONS
  **Trading Route Optimization:**
  - Analyze optimal trading routes based on user's ship, location, and budget
  - Provide real-time commodity price data
  - Calculate profit margins and trading efficiency
  - Recommend best trading opportunities

  **Ship Information Database:**
  - Retrieve detailed specifications for spacecraft
  - Access component and weapon information
  - Compare ship capabilities and performance
  - Provide technical details and recommendations

  ## USER INTERACTION GUIDELINES
  - Always use available StarHead API tools for data retrieval
  - Ask users to specify their current ship, location, and available budget for trading
  - Request clarification for parent objects or specific parameters - never assume
  - Don't provide possible parameter values - always ask users for their specific needs
  - Use "Alpha UEC" (aUEC) as the standard currency reference

  ## EXECUTION PROTOCOL
  - Retrieve live, accurate data from StarHead API for all recommendations
  - Provide detailed trading analysis with current market conditions
  - Give comprehensive ship information based on user queries
  - Always base recommendations on real-time API data rather than assumptions
custom_properties:
  - hint: The URL of the StarHead API.
    id: starhead_api_url
    name: StarHead API URL
    required: true
    value: https://api.star-head.de
    property_type: string
  - hint: The URL of the Star Citizen Wiki API.
    id: star_citizen_wiki_api_url
    name: Star Citizen Wiki API URL
    required: true
    value: https://api.star-citizen.wiki/api/v2
    property_type: string
